version: "3"
services:
  web:
    image: kennethlombardi/get-started:threads
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.9"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/home/ken/docker-swarm-tutorial:/data"
    deploy:
      placement:
        constraints:
          - node.role == manager
    command: redis-server --appendonly yes
