---
- hosts: all
# - hosts: rock64-3.tribal.net:rock64-2.tribal.net
  remote_user: tribal
  become: yes
  tasks:
    - name: test connection
      ping:
      remote_user: tribal
    - name: install dependencies
      remote_user: tribal
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - zsh
        update_cache: yes
        force_apt_get: yes
